services:
  worker_node:
    build:
      context: worker_node
      dockerfile: worker.Dockerfile
    ports:
      - 5000
    volumes:
      - ./worker_node:/app
      - data:/app/data

  master_node:
    build:
      context: master_node
      dockerfile: master.Dockerfile
    ports:
      - 2000:2000
    volumes:
      - ./master_node:/app
      - metadata:/app/metadata

  client_node:
    build:
      context: client_node
      dockerfile: client.Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./client_node/src:/client/src
    depends_on:
      - master_node

volumes:
  metadata:
  data:

networks:
  default:
    name: bigdata
    external: true
